# Generated by Django 3.2.13 on 2023-10-14 00:13

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assessment', '0002_remove_question_bucket'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userresponse',
            unique_together={('user', 'quiz', 'question', 'answer')},
        ),
    ]
