# Generated by Django 3.2.13 on 2023-10-16 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0004_auto_20231016_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='bucket',
            name='inclinations',
            field=models.TextField(blank=True, null=True),
        ),
    ]
