# Generated by Django 3.2.13 on 2023-10-17 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0006_job_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='company',
        ),
    ]
