# Generated by Django 3.2.13 on 2023-10-17 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0007_remove_job_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='bucket',
            name='career_inclination_statement',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bucket',
            name='careers',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bucket',
            name='purpose_statement',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bucket',
            name='thrive_environment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
