# Generated by Django 3.2.13 on 2023-10-18 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0008_auto_20231017_2107'),
    ]

    operations = [
        migrations.AddField(
            model_name='virtue',
            name='text',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
