# Generated by Django 3.2.13 on 2023-10-26 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0011_auto_20231023_1307'),
    ]

    operations = [
        migrations.CreateModel(
            name='Level2Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('bucket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessment.bucket')),
            ],
        ),
        migrations.CreateModel(
            name='Level2Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('negation', models.BooleanField(default=False)),
                ('text', models.CharField(max_length=200)),
                ('options', models.ManyToManyField(to='assessment.Level2Option')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='level2questions', to='assessment.quiz')),
            ],
        ),
    ]
