# Generated by Django 3.2.13 on 2023-10-27 10:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assessment', '0012_level2option_level2question'),
    ]

    operations = [
        migrations.CreateModel(
            name='Level2Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField(default=0)),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessment.level2option')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessment.level2question')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessment.quiz')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'quiz', 'question', 'answer')},
            },
        ),
    ]
