# Generated by Django 3.2.13 on 2023-10-27 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0014_auto_20231027_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='level2response',
            name='nlp',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='level2question',
            name='options',
            field=models.ManyToManyField(blank=True, null=True, to='assessment.Level2Option'),
        ),
    ]
