# Generated by Django 3.2.13 on 2023-10-27 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0015_auto_20231027_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level2response',
            name='answer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assessment.level2option'),
        ),
        migrations.AlterField(
            model_name='level2response',
            name='rank',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
