# Generated by Django 3.2.13 on 2023-10-28 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0016_auto_20231027_1924'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('Level 1', 'Report Level 1'), ('Level 2', 'Report Level 2'), ('Level 3', 'Report Level 3')], max_length=8)),
                ('report_type', models.CharField(choices=[('Career', 'Career'), ('Leadership', 'Leadership'), ('Career + Leadership', 'Career + Leadership')], max_length=20)),
            ],
        ),
    ]
