# Generated by Django 3.2.13 on 2023-10-28 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0017_reporttype'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='report_paid',
            field=models.ManyToManyField(related_name='report_paid', to='assessment.ReportType'),
        ),
    ]
