# Generated by Django 3.2.13 on 2023-10-28 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0018_userprofile_report_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporttype',
            name='level',
            field=models.CharField(choices=[('Level 1', 'Report Level 1'), ('Level 2', 'Report Level 2'), ('Level 3', 'Report Level 3'), ('Level 4', 'Report Level 4')], max_length=8),
        ),
        migrations.AlterField(
            model_name='reporttype',
            name='report_type',
            field=models.CharField(choices=[('Career', 'Career'), ('Leadership', 'Leadership'), ('Career + Leadership', 'Career + Leadership'), ('Talent', 'Talent'), ('Full', 'Full')], max_length=20),
        ),
    ]
