# Generated by Django 3.2.13 on 2023-10-29 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0020_level2bucket'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='level1',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='level2',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='level3',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
