# Generated by Django 3.2.13 on 2023-10-29 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0021_auto_20231030_0502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='level1',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='level2',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='level3',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
