# Generated by Django 3.2.13 on 2023-10-30 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0022_auto_20231030_0510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='report_paid',
            field=models.ManyToManyField(blank=True, null=True, related_name='report_paid', to='assessment.ReportType'),
        ),
    ]
