# Generated by Django 3.2.13 on 2023-10-31 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0023_alter_userprofile_report_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='bucket',
            name='quote',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
