# Generated by Django 3.2.13 on 2023-10-31 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0024_bucket_quote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bucket',
            name='quote',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
