# Generated by Django 3.2.13 on 2023-11-03 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0025_alter_bucket_quote'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningStyles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('statement', models.TextField(blank=True, null=True)),
                ('learnings', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
