# Generated by Django 3.2.13 on 2023-11-03 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0027_auto_20231103_1640'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bucket',
            name='bucket',
        ),
        migrations.AddField(
            model_name='bucket',
            name='virtue',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feature_virtue', to='assessment.virtue'),
        ),
    ]
