# Generated by Django 3.2.13 on 2023-11-04 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0031_trait'),
    ]

    operations = [
        migrations.CreateModel(
            name='Level3Bucket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bucket', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='level3_bucket', to='assessment.bucket')),
                ('fixed_trait2', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='level3_fixedtrait1', to='assessment.trait')),
                ('variable_trait1', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='level3_variabletrait1', to='assessment.trait')),
                ('variable_trait2', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='level3_variabletrait2', to='assessment.trait')),
            ],
        ),
    ]
