# Generated by Django 3.2.13 on 2023-11-04 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0032_level3bucket'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LearningStyles',
            new_name='LearningStyle',
        ),
    ]
