# Generated by Django 3.2.13 on 2023-11-04 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0033_rename_learningstyles_learningstyle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Level3Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('negation', models.BooleanField(default=False)),
                ('text', models.CharField(max_length=200)),
                ('options', models.ManyToManyField(blank=True, null=True, to='assessment.Trait')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='level3questions', to='assessment.quiz')),
            ],
        ),
    ]
