# Generated by Django 3.2.13 on 2023-11-04 09:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assessment', '0034_level3question'),
    ]

    operations = [
        migrations.CreateModel(
            name='Level3Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField(blank=True, null=True)),
                ('answer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assessment.trait')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessment.level3question')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessment.quiz')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'quiz', 'question', 'answer')},
            },
        ),
    ]
