# Generated by Django 3.2.13 on 2023-11-04 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0035_level3response'),
    ]

    operations = [
        migrations.CreateModel(
            name='DecisionMaking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='level3bucket',
            name='fixed_trait2',
        ),
        migrations.RemoveField(
            model_name='level3bucket',
            name='variable_trait1',
        ),
        migrations.RemoveField(
            model_name='level3bucket',
            name='variable_trait2',
        ),
        migrations.AddField(
            model_name='trait',
            name='dimmension',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='level3_trait_bucket', to='assessment.bucket'),
        ),
        migrations.AddField(
            model_name='trait',
            name='type',
            field=models.CharField(choices=[('fixed', 'Fixed'), ('variable', 'Variable')], default='variable', max_length=10),
        ),
    ]
