# Generated by Django 3.2.13 on 2023-11-05 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0039_level3bucket_decision_making'),
    ]

    operations = [
        migrations.CreateModel(
            name='Level3Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('level3_buckets', models.ManyToManyField(related_name='level3_groups', to='assessment.Level3Bucket')),
            ],
        ),
    ]
